In [4]:
import torch
import numpy as np 

torch_scalar = torch.tensor(3.14) 
torch_vector = torch.tensor([1, 2, 3, 4]) 
torch_matrix = torch.tensor([[1, 2,], 
                             [3, 4,], 
                             [5, 6,], 
                             [7, 8,]])
torch_tensor3d = torch.tensor([ 
                             [ 
                             [ 1, 2, 3], 
                             [ 4, 5, 6], 
                             ], 
                             [ 
                             [ 7, 8, 9], 
                             [10, 11, 12], 
                             ], 
                             [ 
                             [13, 14, 15], 
                             [16, 17, 18], 
                             ], 
                             [
                             [19, 20, 21],
                             [22, 23, 24],
                             ] 
                               ])

In [5]:
print(torch_scalar.shape) 
print(torch_vector.shape) 
print(torch_matrix.shape) 
print(torch_tensor3d.shape)

torch.Size([]) 
torch.Size([4]) 
torch.Size([4, 2]) 
torch.Size([4, 2, 3])

torch.Size([])
torch.Size([4])
torch.Size([4, 2])
torch.Size([4, 2, 3])


torch.Size([4, 2, 3])

In [6]:
x_np = np.random.random((4,4)) 
print(x_np) 


x_pt = torch.tensor(x_np) 
print(x_pt) 

[[0.36274766 0.35083073 0.10924672 0.05578504]
 [0.69158577 0.33920569 0.27867026 0.4526325 ]
 [0.44735423 0.67018699 0.18425251 0.13015928]
 [0.56967513 0.45635576 0.31596876 0.58857576]]
tensor([[0.3627, 0.3508, 0.1092, 0.0558],
        [0.6916, 0.3392, 0.2787, 0.4526],
        [0.4474, 0.6702, 0.1843, 0.1302],
        [0.5697, 0.4564, 0.3160, 0.5886]], dtype=torch.float64)


In [7]:
import timeit 
x = torch.rand(2**11, 2**11) 
time_cpu = timeit.timeit("x@x", globals=globals(), number=100)

In [8]:
print("Is CUDA available? :", torch.cuda.is_available()) 
device = torch.device("cuda") 

Is CUDA available? : True


In [9]:
x = x.to(device) 
time_gpu = timeit.timeit("x@x", globals=globals(), number=100)

In [10]:
print("cpu_time: ", time_cpu)
print("gpu_time: ", time_gpu)

cpu_time:  1.818700006000654
gpu_time:  1.1289531830007036


In [11]:
x = torch.tensor([-3.5], requires_grad=True) 
print(x.grad)

None


In [12]:
def f(x):
    return torch.pow((x-2.0), 2)

In [13]:
value = f(x)

In [14]:
print(value)

tensor([30.2500], grad_fn=<PowBackward0>)


In [15]:
value.backward()
print(x.grad)

tensor([-11.])


In [18]:
x = torch.tensor([-3.5], requires_grad=True)

x_cur = x.clone() 
x_prev = x_cur*100

epsilon = 1e-5

eta = 0.1

print(x)

while torch.linalg.norm(x_cur-x_prev) > epsilon:  
    x_prev = x_cur.clone()

    value = f(x)
    value.backward() 
    x.data -= eta * x.grad


    x.grad.zero_()


    x_cur = x.data

    print(x_cur)

tensor([-3.5000], requires_grad=True)
tensor([-2.4000])
tensor([-1.5200])
tensor([-0.8160])
tensor([-0.2528])
tensor([0.1978])
tensor([0.5582])
tensor([0.8466])
tensor([1.0773])
tensor([1.2618])
tensor([1.4094])
tensor([1.5276])
tensor([1.6220])
tensor([1.6976])
tensor([1.7581])
tensor([1.8065])
tensor([1.8452])
tensor([1.8762])
tensor([1.9009])
tensor([1.9207])
tensor([1.9366])
tensor([1.9493])
tensor([1.9594])
tensor([1.9675])
tensor([1.9740])
tensor([1.9792])
tensor([1.9834])
tensor([1.9867])
tensor([1.9894])
tensor([1.9915])
tensor([1.9932])
tensor([1.9946])
tensor([1.9956])
tensor([1.9965])
tensor([1.9972])
tensor([1.9978])
tensor([1.9982])
tensor([1.9986])
tensor([1.9989])
tensor([1.9991])
tensor([1.9993])
tensor([1.9994])
tensor([1.9995])
tensor([1.9996])
tensor([1.9997])
tensor([1.9998])
tensor([1.9998])
tensor([1.9998])
tensor([1.9999])
tensor([1.9999])
tensor([1.9999])
tensor([1.9999])
tensor([1.9999])
tensor([2.0000])
tensor([2.0000])


In [19]:
x_param = torch.nn.Parameter(torch.tensor([-3.5]), requires_grad=True)

In [20]:
optimizer = torch.optim.SGD([x_param], lr=eta)

In [21]:
for epoch in range(60): 
    optimizer.zero_grad()
    loss_incurred = f(x_param) 
    loss_incurred.backward() 
    optimizer.step()
print(x_param.data)

tensor([2.0000])


In [31]:
from torch.utils.data import Dataset
from sklearn.datasets import fetch_openml

X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
print(X.shape)

(70000, 784)


In [32]:
class SimpleDataset(Dataset):
    def __init__(self, X, y): 
        super(SimpleDataset, self).__init__()
        self.X = X 
        self.y = y

    def __getitem__(self, index): 
        inputs = torch.tensor(self.X[index,:], dtype=torch.float32)
        targets = torch.tensor(int(self.y[index]), dtype=torch.int64) 
        return inputs, targets

    def __len__(self): 
        return self.X.shape[0]
    

dataset = SimpleDataset(X, y)

In [33]:
print("Length: ", len(dataset)) 
example, label = dataset[0]
print("Features: ", example.shape)
print("Label of index 0: ", label) 


Length:  70000


TypeError: '(0, slice(None, None, None))' is an invalid key